### ISSUE TITLE
RangeError when creating colliders

### ISSUE THREAD

**Issue by chungwu** [dimforge/rapier.js#262]
I'm using 2D rapier.js.  When creating a collider, I sometimes see this error:

```
RangeError: Invalid array length
      at Array.push (<anonymous>)
      at Coarena.set (party/index.ts:12939:17)
      at ColliderSet.createCollider (party/index.ts:17125:14)
      at _World.createCollider (party/index.ts:15592:27)
```

It looks like the issue is coming from Coarena, where `Coarena.index(handle)` is returning an unexpectedly large number that exceeds the possible array length.

Relevant snippet of Coarena:

```
export class Coarena {
    constructor() {
        this.fconv = new Float64Array(1);
        this.uconv = new Uint32Array(this.fconv.buffer);
        this.data = new Array();
        this.size = 0;
    }
    index(handle) {
        /// Extracts the index part of a handle (the lower 32 bits).
        /// This is done by first injecting the handle into an Float64Array
        /// which is itself injected into an Uint32Array (at construction time).
        /// The 0-th value of the Uint32Array will become the `number` integer
        /// representation of the lower 32 bits.
        /// Also `this.uconv[1]` then contains the generation number as a `number`,
        /// which we don’t really need.
        this.fconv[0] = handle;
        return this.uconv[0];
    }
    set(handle, data) {
        let i = this.index(handle);
        while (this.data.length <= i) {
            // ERROR COMES FROM THIS data.push() pushing past array length limit
            this.data.push(null);
        }
        if (this.data[i] == null)
            this.size += 1;
        this.data[i] = data;
    }
}
```

In my case, the handle passed to `set()` was `2.7161131672e-312`, which is translated to index `4286578687`.  Interestingly, **the failure case is always with the handle `2.7161131672e-312`**.  This doesn't happen every time I call `createCollider()`; it only happens "after a few times".  And once it fails, it always fails with the same handle, until I restart the server, in which case it will work for a little while until it produces that same handle again.

The handle is directly coming from `RawColliderSet.createCollider()`, which calls into the wasm code.  Not sure whether this is an invalid handle? (so the issue is with the wasm rust code), or if the conversion to index is incorrect? (so the issue is with the js wrapper).

Thanks!

**Comment by chungwu** [comment]
Specifically, I'm seeing these as the high and low bits of the handle:

```
High bits: 00000000000000000000000001111111
Low bits: 11111111011111111111111111111111
Combined: 0000000000000000000000000111111111111111011111111111111111111111
```

This definitely looks pretty unusual :thinking:

**Comment by chungwu** [comment]
I think this is my user error, caused by a hot-reloading server that is loading the wasm module multiple times. Closing.
