### ISSUE TITLE
RuntimeError: unreachable when using RAPIER.JointData.spring

### ISSUE THREAD

**Issue by MaxBittker** [dimforge/rapier.js#268]
I was able to use all other joint type, but not springs. Not sure how to debug this further as
the error just looks like this:
```
003fd91e:0xbf827 Uncaught (in promise) RuntimeError: unreachable
    at 003fd91e:0xbf827
    at 003fd91e:0xec82b
    at 003fd91e:0xe0612
    at 003fd91e:0x41831
    at 003fd91e:0x12014
    at 003fd91e:0x199ae
    at 003fd91e:0xa061b
    at RawPhysicsPipeline.step (rapier_wasm2d_bg.js:2696:14)
    at PhysicsPipeline.step (physics_pipeline.ts:69:22)
    at _World.step (world.ts:241:30)
```    
    
Here is a reproduction case: 
https://codesandbox.io/p/devbox/busy-hamilton-f947s2?

(change line 88 to use ropeJointParams to see a working version)

**Comment by MaxBittker** [comment]
this is solved if i build from b00113ed2f9e4824a254027b57c9b4a07c4c2307
